### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by JorgenPhi** [ezhes/OSXMessageProxy#5]
I'd like to start by saying this is awesome. I was *this* close to writing my own before I saw this project. It is quite literally the solution for iMessage that I have been searching for. 

Anyways, I know that the API key is there for "protection", but adding in native TLS support would be a huge plus. Right now I have nginx in the middle to handle the TLS encryption, but it's far from an elegant setup.

**Comment by shusain93** [comment]
Definitely on the road map. I am fully aware that this is unsafe and really the API key is only to stop you from leaking your IP and other people here stealing your messages. 

The issue is that the web server doesn't support SSL at all so I would have to completely switch to a new networking framework. Shouldn't be too hard but it's taking the back burner since adding socket communication to provide live messaging is more important

**Comment by shusain93** [comment]
Quick update for you: I've found a perfect way to get SSL for all communication on the server, including the sockets. The kitura framework from IBM is pretty incredible. The bad news is that I've not done any of this yet and am out of time this weekend and I'll have to redo the whole socket interface again because I'm going to have to move from raw TCP sockets (which seem to be pretty unreliable as it turns out , especially on mobile networks) to SSL encrypted web sockets. Next weekend seems possible?
